name: cpp-dev-prj

services:
  cpp-dev:
    image: cpp-dev-img
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-dev-cont
    user: cppuser  # non-root user
    volumes:
      - ./:/workspace # mount the current directory to /workspace
    cap_add:
      - SYS_PTRACE
    stdin_open: true  # -i (interactive)
    tty: true         # -t (pseudo-TTY)
    # command: tail -f /dev/null # or command: /bin/bash
    command: /bin/bash -c "echo 'cpp-dev service is running. 
                           If your terminal is stuck, press CTRL+C and use \"docker compose up -d\" 
                           to launch this service in background (detached mode).' && 
                           echo 'Then, to link again to this service use \"docker compose exec cpp-dev /bin/bash\".' && 
                           tail -f /dev/null"
    restart: unless-stopped

networks:
  default:
    name: cpp-dev-net