name: cpp-dev-prj

services:
  cpp-dev-srv:
    image: cpp-dev:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: cpp-dev-cont

    environment:
      - WORK_DIR=/workspace

    user: cppuser  # non-root user

    volumes:
      - ./:/workspace # mount the current directory to WORKDIR in the container

    cap_add:
      - SYS_PTRACE # for gdb, remove if in production

    security_opt:
      - seccomp:unconfined # for gdb, remove if in production

    stdin_open: true  # -i (interactive)
    tty: true         # -t (pseudo-TTY)

    command: /bin/bash -c "echo 'cpp-dev service is running. 
                           If your terminal is stuck, press CTRL+C and use \"docker compose up -d\" 
                           to launch this service in background (detached mode).' && 
                           echo 'Then, to link again to this service use \"docker compose exec cpp-dev /bin/bash\".' && 
                           tail -f /dev/null"

    restart: unless-stopped

networks:
  default:
    name: cpp-dev-net